<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Main</title>
</head>
<body>
<?php if($currentUser) : ?>
  <div class="container mt-5">
    <div class="card col-sm-9 mx-auto">
      <div class="row">
        <div class="col-md-4">
          <?php if($userData['image']) :?>
          <img src="<?=$userData['image'] ?>" class="card-img mt-3 mb-3" alt="user_image">
          <?php else : ?>
          <svg class="bd-placeholder-img img-fluid mt-4 mb-4 " width="300" height="300" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera: 200x200">
            <rect fill="#868e96" width="100%" height="100%"></rect>
            <text fill="#dee2e6" dy=".5em" x="25%" y="50%">No image</text>
          </svg>
          <?php endif; ?>
          <form action="/sign_out" method="post">
            <button type="submit" class="btn btn-primary col-12 mb-3">LogOut</button>
          </form>
          <form action="/ru" method="post">
          <button type="submit" class="btn col-12 btn-outline-info mt-2 mb-3">Русский</button>
        </form>
        </div>
        <div class="col-md-8">
          <div class="card-body">
            <h5 class="card-title"><?= htmlspecialchars($userData['login']) ?></h5>
            <table class="table">
              <tr>
                <td>phone</td>
                <td><?= htmlspecialchars($userData['phone']) ?></td>
              </tr>
              <tr>
                <td>email</td>
                <td><?= htmlspecialchars($userData['email']) ?></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
      
    </div>
  </div>
<?php else: ?>
<div class="container">

</div>
  <div class="container mt-5 ">
    <div class="row ">
      <div class="col-sm-5 col-12 mx-auto mt-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">SignIn</h5>
            <form action="/sign_in" method="post">
              <div class="form-group">
                <label for="exampleInputEmail1">Login</label>
                <input type="text" class="form-control <?= $errorLogin ? ' is-invalid' : null?>" id="exampleInputEmail1" name="login">
                <?= $errorLogin ? "<div class='invalid-feedback'>{$errorLogin}</div>" : null ?>
                
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control<?= $errorPassword ? ' is-invalid' : null?>" id="exampleInputPassword1" name="password">
                <?= $errorPassword ? "<div class='invalid-feedback'>{$errorPassword}</div>" : null ?>
              </div>
              <button type="submit" class="btn btn-primary col-12 mt-3">SignIn</button>
            </form>
          </div>
        </div>
        <div class="card mt-3">
          <div class="card-body text-center">
             <span>Don't have an account yet?<a href="/users/new"> Register!</a></span>
          </div>
        </div>
        <form action="/ru" method="post">
          <button type="submit" class="btn col-3 btn-outline-info mt-3">Русский</button>
        </form>
    </div>
  </div>
</div>
<?php endif; ?>
</body>
</html>