<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Succes</title>
</head>
<body>
<div class="container text-center" style="margin-top: 400px">
    <div class="card-body mt-5 col-6 mx-auto ">
      <h5 class="card-title">Registration was successful!</h5>
      <a href="/" class="btn btn-primary">Back to main page</a>
    </div>
  </div>
</body>
</html>