<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Главная</title>
</head>
<body>
  <div class="container mt-5 ">
    <div class="row ">
      <div class="col-sm-5 col-12 mx-auto mt-5">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title">Войти</h5>
            <form>
              <div class="form-group">
                <label for="exampleInputEmail1">Email или логин</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
                <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
              </div>
              <div class="form-group">
                <label for="exampleInputPassword1">Пароль</label>
                <input type="password" class="form-control" id="exampleInputPassword1">
                
              </div>
              <button type="submit" class="btn btn-primary col-12 mt-3">Войти</button>
            </form>
          </div>
        </div>
        <div class="card mt-3">
          <div class="card-body text-center">
             <span>Еще нет аккаунта? <a href="/users/new">Зарегистрироваться!</a></span>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>
</html>