<!DOCTYPE html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <title>Регистрация</title>
</head>
<body>
  <div class="container mt-3">
    <div class="row">
      <div class="col-sm-5 col-12 mx-auto mt-4">
        <div class="card">
          <div class="card-body">
            <h5 class="card-title mb-4">Регистрация</h5>
            <form action="/users" method="post" enctype="multipart/form-data" data-form="sign-up">
              <div class="form-group">
                <label for="InputLogin">Логин*</label>
                <input type="text" class="form-control" id="InputLogin" name="login">
              </div>
              <div class="form-group">
                <label for="InputEmail1">Email*</label>
                <input type="email" class="form-control" id="InputEmail1" name="email">
              </div>
              <div class="form-group">
                <label for="InputPhone">Телефон</label>
                <input type="tel" name="phone" id="InputPhone" class="form-control bfh-phone"/>
              </div>
              <div class="form-group">
                <label for="InputPassword1">Пароль*</label>
                <input type="password" class="form-control" id="InputPassword1" name="password">
              </div>
              <div class="form-group">
                <label for="InputPassword2">Повторите пароль*</label>
                <input type="password" class="form-control" id="InputPassword2" name="password_confirm">
              </div>
              <div class="form-group">
              <label for="customFileLangHTML">Прикрепить файл:</label>

                <div class="custom-file">
                  <input type="file" class="custom-file-input" id="customFileLangHTML" name="image_file">
                  <label class="custom-file-label" for="customFileLangHTML" data-browse="Файл"><small class="form-text text-muted">Допустимые форматы: png, jpeg, gif</small></label>
                </div>
                <small class="form-text text-muted">Размер файла не должен превышать 10 Мб.</small>
              </div>
              
              <button type="submit" class="btn btn-primary col-12 mt-2" id='submitButton' disabled>Зарегестрироваться</button>
            </form>
          </div>
        </div>
        <div class="card mt-3">
          <div class="card-body text-center">
             <span>Уже есть аккаунт? <a href="/">Войти</a></span>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input/dist/bs-custom-file-input.min.js"></script>
  <script src="/scripts/main.js"></script>
</body>
</html>